---
version: '3'

services:
  s3-sync-entrypoint:
    container_name: s3-sync-entrypoint
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/s3-sync-entrypoint:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/s3-sync-entrypoint
